name: web
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cloud_firestore: 0.14.2
  cupertino_icons: ^1.0.1
  firebase_auth: 0.18.2
  firebase_core: 0.5.1
  flutter_phoenix: ^0.1.0
  flutter_screenutil: ^4.0.0
  flutter_svg: ^0.19.3
  fluttertoast: ^7.1.5
  form_field_validator: ^1.0.1
  get: ^4.0.0-nullsafety.2
  get_it: ^5.0.3
  getwidget: ^1.2.4
  image_picker: ^0.6.7+15
  lite_rolling_switch: ^0.1.1
  responsive_framework: ^0.0.14
  uuid: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
